apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: claud-project
spec:
  selector:
    app: sqlserver
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
      nodePort: 30080  
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: claud-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          emptyDir: {}
