apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:80
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ReportingServiceDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
