apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS:  http://+:80
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=TransactionServiceDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
