apiVersion: v1
kind: Service
metadata:
  name: usermanagementservice
  namespace: claud-project
spec:
  selector:
    app: usermanagementservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081    
  type: NodePort
