version: '3.8'

services:
  usermanagementservice:
    build:
      context: ./UserManagementService
      dockerfile: Dockerfile
    ports:
      - "6062:80"
    depends_on:
      - sqlserver-dev4
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-dev4;Database=UserManagemntServiceDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - app-network-test

  transactionservice:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile
    ports:
      - "6063:80"
    depends_on:
      - sqlserver-dev4
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-dev4;Database=UserManagemntServiceDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - app-network-test

  reportingservice:
    build:
      context: ./ReportingService
      dockerfile: Dockerfile
    ports:
      - "6064:80"
    depends_on:
      - sqlserver-dev4
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-dev4;Database=UserManagemntServiceDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - app-network-test

  notificationapi:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "6065:80"
    depends_on:
      - sqlserver-dev4
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-dev4;Database=UserManagemntServiceDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - app-network-test

  sqlserver-dev4:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1435:1433"
    volumes:
      - sqldata-test:/var/opt/mssql
    networks:
      - app-network-test

networks:
  app-network-test:
    driver: bridge

volumes:
  sqldata-test:
