apiVersion: v1
kind: Service
metadata:
  name: transactionservice
  namespace: claud-project
spec:
  selector:
    app: transactionservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082   
  type: NodePort
