apiVersion: v1
kind: Service
metadata:
  name: reportingservice
  namespace: claud-project
spec:
  selector:
    app: reportingservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083    
  type: NodePort
